using MediatR;
using Microsoft.Extensions.Logging;
using ValyanClinic.Application.Common.Results;
using ValyanClinic.Domain.Interfaces.Repositories;
using ValyanClinic.Domain.Interfaces.Security;

namespace ValyanClinic.Application.Features.UtilizatorManagement.Commands.ChangePassword;

public class ChangePasswordCommandHandler : IRequestHandler<ChangePasswordCommand, Result<bool>>
{
    private readonly IUtilizatorRepository _repository;
    private readonly IPasswordHasher _passwordHasher;
    private readonly ILogger<ChangePasswordCommandHandler> _logger;

    public ChangePasswordCommandHandler(
        IUtilizatorRepository repository,
   IPasswordHasher passwordHasher,
   ILogger<ChangePasswordCommandHandler> logger)
    {
        _repository = repository;
        _passwordHasher = passwordHasher;
        _logger = logger;
    }

    public async Task<Result<bool>> Handle(ChangePasswordCommand request, CancellationToken cancellationToken)
    {
        try
        {
            _logger.LogInformation("Schimbare parola pentru utilizator: {UtilizatorID}", request.UtilizatorID);

            // Validate user exists
            var utilizator = await _repository.GetByIdAsync(request.UtilizatorID, cancellationToken);
            if (utilizator == null)
            {
                _logger.LogWarning("Utilizatorul nu a fost gasit: {UtilizatorID}", request.UtilizatorID);
                return Result<bool>.Failure("Utilizatorul nu a fost gasit");
            }

            // Hash new password with BCrypt
            var newPasswordHash = _passwordHasher.HashPassword(request.NewPassword);
            var salt = "bcrypt_autogenerated"; // BCrypt include salt automat

            // Update password in repository
            var success = await _repository.ChangePasswordAsync(
                         request.UtilizatorID,
               newPasswordHash,
             salt,
         request.ModificatDe,
               cancellationToken);

            if (!success)
            {
                _logger.LogError("Eroare la schimbarea parolei in repository");
                return Result<bool>.Failure("Eroare la salvarea noii parole");
            }

            _logger.LogInformation("Parola schimbata cu succes pentru: {UtilizatorID}", request.UtilizatorID);
            return Result<bool>.Success(true, "Parola a fost schimbata cu succes");
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Eroare la schimbarea parolei pentru: {UtilizatorID}", request.UtilizatorID);
            return Result<bool>.Failure($"Eroare: {ex.Message}");
        }
    }
}
