-- ========================================
-- SQL Script: Create Admin Superuser
-- Database: ValyanMed
-- Descriere: Creeaz? utilizatorul Admin direct în database
-- Username: Admin
-- Password: admin123!@#
-- Autor: System
-- Data: 2025-01-24
-- ========================================

USE [ValyanMed]
GO

-- Set options for proper execution
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
SET ANSI_WARNINGS ON
GO

PRINT '========================================';
PRINT ' CREATE ADMIN SUPERUSER';
PRINT '========================================';
PRINT '';

-- ========================================
-- STEP 1: Verificare ?i ?tergere utilizator existent
-- ========================================

PRINT 'Step 1: Verificare utilizator existent...';

IF EXISTS (SELECT 1 FROM Utilizatori WHERE Username = 'Admin')
BEGIN
PRINT '  WARNING: Utilizatorul Admin exist? deja - se ?terge...';
    DELETE FROM Utilizatori WHERE Username = 'Admin';
    PRINT '  OK: Utilizatorul existent a fost ?ters';
END
ELSE
BEGIN
    PRINT '  OK: Utilizatorul Admin nu exist? - poate fi creat';
END

PRINT '';

-- ========================================
-- STEP 2: Creare/Verificare PersonalMedical pentru Admin
-- ========================================

PRINT 'Step 2: Creare PersonalMedical pentru Admin...';

DECLARE @PersonalMedicalID UNIQUEIDENTIFIER;

-- Check if PersonalMedical for Admin exists
SELECT @PersonalMedicalID = PersonalID 
FROM PersonalMedical 
WHERE Nume = 'System' AND Prenume = 'Administrator';

IF @PersonalMedicalID IS NULL
BEGIN
    PRINT '  INFO: PersonalMedical pentru Admin nu exist? - se creeaz?...';
  
    SET @PersonalMedicalID = NEWID();
    
    INSERT INTO PersonalMedical (
        PersonalID,
  Nume,
        Prenume,
        Email,
        Telefon,
 Specializare,
        Departament,
        Pozitie,
        EsteActiv,
        DataCreare
    )
    VALUES (
        @PersonalMedicalID,
        'System',
        'Administrator',
     'admin@valyan.clinic',
        NULL,
   'Administrare Sistem',
        'IT',
        'Super Administrator',
        1,
        GETDATE()
    );
    
    PRINT '  OK: PersonalMedical creat cu ID: ' + CAST(@PersonalMedicalID AS NVARCHAR(50));
END
ELSE
BEGIN
    PRINT '  OK: PersonalMedical g?sit cu ID: ' + CAST(@PersonalMedicalID AS NVARCHAR(50));
END

PRINT '';

-- ========================================
-- STEP 3: Creare utilizator Admin
-- ========================================

PRINT 'Step 3: Creare utilizator Admin...';

DECLARE @UtilizatorID UNIQUEIDENTIFIER = NEWID();
DECLARE @Username NVARCHAR(100) = 'Admin';
DECLARE @Email NVARCHAR(100) = 'admin@valyan.clinic';
-- ? REAL BCrypt hash pentru "admin123!@#" cu Work Factor 12
-- Generat cu BCrypt.Net-Next v4.0.3
DECLARE @PasswordHash NVARCHAR(256) = '$2a$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMesbjx.U4T6wgSJc4xE7iW.Im'; 
DECLARE @Salt NVARCHAR(100) = 'bcrypt_autogenerated'; -- BCrypt include salt automat în hash
DECLARE @Rol NVARCHAR(50) = 'Administrator';

BEGIN TRY
    INSERT INTO Utilizatori (
        UtilizatorID,
        PersonalMedicalID,
    Username,
   Email,
 PasswordHash,
        Salt,
        Rol,
        EsteActiv,
        DataCreare,
        CreatDe,
        DataCrearii,
        DataUltimeiModificari
    )
    VALUES (
        @UtilizatorID,
        @PersonalMedicalID,
  @Username,
        @Email,
        @PasswordHash,
        @Salt,
   @Rol,
   1,
        GETDATE(),
      'System',
        GETDATE(),
        GETDATE()
    );
    
    PRINT '  OK: Utilizator Admin creat cu succes!';
    PRINT '';
    PRINT '  UtilizatorID: ' + CAST(@UtilizatorID AS NVARCHAR(50));
    PRINT '  Username:     ' + @Username;
    PRINT '  Email:        ' + @Email;
    PRINT '  Rol:          ' + @Rol;
END TRY
BEGIN CATCH
    PRINT '  ERROR: ' + ERROR_MESSAGE();
    PRINT '';
    THROW;
END CATCH

PRINT '';

-- ========================================
-- STEP 4: Verificare
-- ========================================

PRINT 'Step 4: Verificare utilizator creat...';

SELECT 
    u.UtilizatorID,
 u.Username,
    u.Email,
    u.Rol,
    u.EsteActiv,
    u.DataCreare,
    pm.Nume + ' ' + pm.Prenume AS PersonalMedical,
    pm.Specializare
FROM Utilizatori u
INNER JOIN PersonalMedical pm ON u.PersonalMedicalID = pm.PersonalID
WHERE u.Username = 'Admin';

PRINT '';
PRINT '========================================';
PRINT ' ADMIN SUPERUSER CREAT CU SUCCES!';
PRINT '========================================';
PRINT '';
PRINT 'CREDENTIALE:';
PRINT '  Username: Admin';
PRINT '  Password: admin123!@#';
PRINT '  Email:    admin@valyan.clinic';
PRINT '';
PRINT 'IMPORTANT: Schimb? parola dup? prima autentificare!';
PRINT '';
GO
