using MediatR;
using Microsoft.Extensions.Logging;
using ValyanClinic.Application.Common.Results;
using ValyanClinic.Domain.Entities;
using ValyanClinic.Domain.Interfaces.Repositories;
using ValyanClinic.Domain.Interfaces.Security;

namespace ValyanClinic.Application.Features.UtilizatorManagement.Commands.CreateUtilizator;

public class CreateUtilizatorCommandHandler : IRequestHandler<CreateUtilizatorCommand, Result<Guid>>
{
    private readonly IUtilizatorRepository _repository;
    private readonly IPasswordHasher _passwordHasher;
    private readonly ILogger<CreateUtilizatorCommandHandler> _logger;

    public CreateUtilizatorCommandHandler(
  IUtilizatorRepository repository,
   IPasswordHasher passwordHasher,
        ILogger<CreateUtilizatorCommandHandler> logger)
    {
        _repository = repository;
        _passwordHasher = passwordHasher;
        _logger = logger;
    }

    public async Task<Result<Guid>> Handle(CreateUtilizatorCommand request, CancellationToken cancellationToken)
    {
        try
        {
            _logger.LogInformation("Creare utilizator: {Username} pentru PersonalMedicalID: {PersonalMedicalID}",
             request.Username, request.PersonalMedicalID);

            // Validate username uniqueness
            var existingByUsername = await _repository.GetByUsernameAsync(request.Username, cancellationToken);
            if (existingByUsername != null)
            {
                _logger.LogWarning("Username deja existent: {Username}", request.Username);
                return Result<Guid>.Failure("Username-ul este deja folosit");
            }

            // Validate email uniqueness
            var existingByEmail = await _repository.GetByEmailAsync(request.Email, cancellationToken);
            if (existingByEmail != null)
            {
                _logger.LogWarning("Email deja existent: {Email}", request.Email);
                return Result<Guid>.Failure("Email-ul este deja folosit");
            }

            // ✅ REAL BCrypt hashing (Work Factor 12)
            var passwordHash = _passwordHasher.HashPassword(request.Password);

            // ✅ BCrypt include salt-ul automat în hash, dar păstrăm coloana Salt pentru compatibility
            // Marcăm că folosim BCrypt
            var salt = "bcrypt_autogenerated";

            var utilizator = new Utilizator
            {
                UtilizatorID = Guid.NewGuid(),
                PersonalMedicalID = request.PersonalMedicalID,
                Username = request.Username,
                Email = request.Email,
                PasswordHash = passwordHash,
                Salt = salt,
                RolID = request.RolID,
                EsteActiv = request.EsteActiv,
                DataCreare = DateTime.Now,
                CreatDe = request.CreatDe,
                DataCrearii = DateTime.Now,
                DataUltimeiModificari = DateTime.Now,
                NumarIncercariEsuate = 0
            };

            var utilizatorID = await _repository.CreateAsync(utilizator, cancellationToken);

            if (utilizatorID == Guid.Empty)
            {
                _logger.LogError("Eroare la crearea utilizatorului in repository");
                return Result<Guid>.Failure("Eroare la salvarea utilizatorului");
            }

            _logger.LogInformation("Utilizator creat cu succes: {UtilizatorID}, PasswordHash length: {Length}",
        utilizatorID, passwordHash.Length);
            return Result<Guid>.Success(utilizatorID, "Utilizator creat cu succes");
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Eroare la crearea utilizatorului: {Username}", request.Username);
            return Result<Guid>.Failure($"Eroare: {ex.Message}");
        }
    }
}
